# Extra autostart processes
# exec-once = uwsm-app -- my-service
windowrulev2 = workspace 1, class:^(ghostty)$
windowrulev2 = workspace 2, class:^(chromium)$
windowrulev2 = workspace 3, class:^(code)$
windowrulev2 = workspace 4, class:^(chrome-discord.com__channels_@me-Default)$
windowrulev2 = workspace 4, class:^(chrome-web.whatsapp.com__-Default)$

exec-once = [workspace 1 silent] ghostty
exec-once = [workspace 2 silent] chromium
exec-once = [workspace 3 silent] code
exec-once = [workspace 4 silent] chromium --app=https://discord.com/channels/@me
exec-once = [workspace 4 silent] chromium --app=https://web.whatsapp.com
exec-once = hyprswitch init --show-title --size-factor 6 --workspaces-per-row 5 &
exec-once = hyprctl dispatch workspace 1
